import { Deck } from "@/types/slides";
import { c, ink } from "@/lib/colors";

export const HARDCODED_DECK: Deck = {
  id: "deck-001",
  title: "Campfire Demo",
  slides: [
    {
      id: "slide-001",
      background: { type: "color", value: "#ffffff" },
      notes: "",
      elements: [
        {
          id: "el-001-title",
          type: "text",
          rect: { x: 160, y: 420, width: 1600, height: 140 },
          zIndex: 1,
          content: "Welcome to Campfire 🔥",
          runs: [],
          style: {
            fontFamily: "Inter, sans-serif",
            fontSize: 96,
            fontWeight: 700,
            fontStyle: "normal",
            textDecoration: "none",
            color: "#111111",
            textAlign: "center",
            lineHeight: 1.2,
            letterSpacing: -2,
          },
        },
        {
          id: "el-001-subtitle",
          type: "text",
          rect: { x: 410, y: 590, width: 1100, height: 70 },
          zIndex: 2,
          content: "A WYSIWYG editor for reveal.js presentations",
          runs: [],
          style: {
            fontFamily: "Inter, sans-serif",
            fontSize: 36,
            fontWeight: 400,
            fontStyle: "normal",
            textDecoration: "none",
            color: ink(0.45),
            textAlign: "center",
            lineHeight: 1.5,
            letterSpacing: 0,
          },
        },
      ],
    },
    {
      id: "slide-002",
      background: { type: "color", value: "#ffffff" },
      notes: "",
      elements: [
        {
          id: "el-002-heading",
          type: "text",
          rect: { x: 120, y: 320, width: 820, height: 120 },
          zIndex: 1,
          content: "Built for Creators",
          runs: [],
          style: {
            fontFamily: "Inter, sans-serif",
            fontSize: 72,
            fontWeight: 700,
            fontStyle: "normal",
            textDecoration: "none",
            color: "#111111",
            textAlign: "left",
            lineHeight: 1.2,
            letterSpacing: -1,
          },
        },
        {
          id: "el-002-body",
          type: "text",
          rect: { x: 120, y: 480, width: 820, height: 280 },
          zIndex: 2,
          content: "Drag, drop, and edit your slides visually.\nNo code required.",
          runs: [],
          style: {
            fontFamily: "Inter, sans-serif",
            fontSize: 40,
            fontWeight: 400,
            fontStyle: "normal",
            textDecoration: "none",
            color: ink(0.6),
            textAlign: "left",
            lineHeight: 1.6,
            letterSpacing: 0,
          },
        },
        {
          id: "el-002-image",
          type: "image",
          rect: { x: 1080, y: 200, width: 680, height: 680 },
          zIndex: 3,
          src: "https://upload.wikimedia.org/wikipedia/commons/0/0f/Campfire_Pinecone.png",
          objectFit: "cover",
          borderRadius: 16,
        },
      ],
    },
    {
      id: "slide-003",
      background: { type: "color", value: "#ffffff" },
      notes: "",
      elements: [
        {
          id: "el-003-cta",
          type: "text",
          rect: { x: 160, y: 460, width: 1600, height: 160 },
          zIndex: 1,
          content: "Start presenting today.",
          runs: [],
          style: {
            fontFamily: "Inter, sans-serif",
            fontSize: 88,
            fontWeight: 700,
            fontStyle: "normal",
            textDecoration: "none",
            color: c.brand,
            textAlign: "center",
            lineHeight: 1.2,
            letterSpacing: -2,
          },
        },
      ],
    },
  ],
};
